name: Continuous integration

on:
  push:
    branches-ignore:
      - "wip*"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"

jobs:
  rust_check:
    name: Rust code checks
    runs-on: rust-latest
    steps:
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - uses: actions/checkout@v6
      - uses: https://github.com/Swatinem/rust-cache@v2
        with:
          cache-on-failure: true # useful for don't rebuild dependencies on fix after failure
      - name: "Cargo formatting"
        if: $${{ always() }}
        run: cargo fmt --all -- --check
      - name: "Cargo clippy"
        if: $${{ always() }}
        run: cargo clippy --profile=test --all-targets --all-features --locked
      - name: "Cargo doc"
        if: $${{ always() }}
        run: cargo doc --locked --all-features --no-deps
      - name: "Cargo test"
        if: $${{ always() }}
        run: cargo test --all-targets --all-features --locked
      - name: "unused dependencies"
        if: $${{ always() }}
        uses: https://github.com/bnjbvr/cargo-machete@main

  toml_checks:
    name: Toml files checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker://docker.io/tamasfe/taplo:latest
        with:
          args: fmt --check --diff

  typos_checks:
    name: Typos check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check spelling of entire workspace
        uses: https://github.com/crate-ci/typos@master
